from spread import Spread


class Reading:
    def __init__(self, deck):
        self.deck = deck
        self.spreads = self._initialize_spreads()

    def _initialize_spreads(self):
        return {
            "past_present_future": Spread(
                "past_present_future",
                "This spread provides a quick snapshot of your life by examining the past, present, and future. Use it to gain insight into how past events influence your current situation and what you can expect moving forward. It's great for general queries or specific issues where you need concise guidance on how past actions are impacting your present and what future trajectory you are on.",
                [
                    "How will my current relationship develop?",
                    "What should I focus on in my career?",
                    "How can I overcome recent challenges?",
                ],
                ["Past", "Present", "Future"],
            ),
            "celtic_cross": Spread(
                "celtic_cross",
                "The Celtic Cross is a comprehensive spread that covers various aspects of your life, offering a deep dive into your current situation, challenges, influences, and potential outcomes. It's ideal for complex issues where you need detailed guidance. Use this spread to understand the dynamics at play in situations involving relationships, career decisions, or personal growth.",
                [
                    "What are the challenges and influences affecting my current project?",
                    "How can I improve my relationship?",
                    "What is the best path for my spiritual development?",
                ],
                [
                    "Present",
                    "Challenge",
                    "Past",
                    "Future",
                    "Above",
                    "Below",
                    "Advice",
                    "External Influences",
                    "Hopes and Fears",
                    "Outcome",
                ],
            ),
            "horseshoe": Spread(
                "horseshoe",
                "This spread is useful for gaining insight into your past, present, and future, while also revealing hidden influences and obstacles. It provides a balanced view of your situation, helping you make informed decisions. Use the Horseshoe spread for queries about ongoing situations where you need to understand the unseen factors and potential challenges.",
                [
                    "What hidden factors should I consider in my career change?",
                    "What obstacles might I face in my relationship?",
                    "How can I best navigate this personal conflict?",
                ],
                [
                    "Past",
                    "Present",
                    "Hidden Influences",
                    "Obstacles",
                    "External Influences",
                    "Suggested Action",
                    "Outcome",
                ],
            ),
            "relationship": Spread(
                "relationship",
                "This spread delves into the dynamics of your relationship, identifying strengths, weaknesses, and future potential. Use it to gain clarity on your partnership, whether it’s romantic, familial, or platonic. This spread is ideal for understanding how to improve the relationship and what to expect moving forward.",
                [
                    "What are the strengths and weaknesses of my relationship?",
                    "How can I better understand my partner?",
                    "What is the future potential of this relationship?",
                ],
                ["You", "Partner", "Foundation", "Strengths", "Weaknesses", "Future"],
            ),
            "astrological": Spread(
                "astrological",
                "The Astrological spread provides a detailed analysis of various life aspects by corresponding each card to the twelve houses of astrology. It offers insights over a period of time and is useful for understanding influences in different areas such as home, career, relationships, and personal growth.",
                [
                    "What should I focus on in my career this year?",
                    "How will my home life change?",
                    "What are the major influences affecting my personal growth?",
                ],
                [f"House {i}" for i in range(1, 13)],
            ),
            "yearly": Spread(
                "yearly",
                "This spread offers a month-by-month outlook for the year ahead, highlighting key events and influences for each month. It’s perfect for planning and preparing for what’s to come. Use this spread to understand the overall themes and significant changes each month will bring.",
                [
                    "What major events should I prepare for this year?",
                    "How can I best navigate the coming months?",
                    "What should be my focus each month to achieve my goals?",
                ],
                [f"Month {i}" for i in range(1, 13)],
            ),
            "karmic": Spread(
                "karmic",
                "The Karmic spread explores influences from past lives, your current life purpose, and karmic lessons to provide insights on how your past affects your present and future. Use this spread to understand deep-rooted issues and spiritual lessons.",
                [
                    "What past life influences are affecting me now?",
                    "What is my current life purpose?",
                    "What karmic lessons do I need to learn?",
                ],
                [
                    "Past Life",
                    "Current Life Purpose",
                    "Karmic Lessons",
                    "Future Life Influence",
                ],
            ),
            "elemental": Spread(
                "elemental",
                "This spread uses the four elements (Fire, Water, Air, Earth) to offer insight into various areas of your life and how they interconnect. It’s great for understanding the balance between different life aspects and how to harmonize them.",
                [
                    "How can I balance my work and personal life?",
                    "What areas need more attention?",
                    "How can I achieve harmony in my relationships?",
                ],
                ["Fire", "Water", "Air", "Earth"],
            ),
            "career": Spread(
                "career",
                "The Career spread focuses on your professional life, identifying your current position, challenges, strengths, opportunities, advice, and potential outcomes. Use it to gain clarity on career decisions and paths.",
                [
                    "What are my career strengths and challenges?",
                    "How can I advance in my current job?",
                    "What opportunities should I pursue for career growth?",
                ],
                [
                    "Current Position",
                    "Challenges",
                    "Strengths",
                    "Opportunities",
                    "Advice",
                    "Outcome",
                ],
            ),
            "journey": Spread(
                "journey",
                "This spread provides guidance on your life’s journey, exploring starting points, current positions, challenges, hidden influences, guidance, and outcomes. It’s useful for understanding where you are on your path and what steps to take next.",
                [
                    "What is my current position on my life path?",
                    "What challenges lie ahead?",
                    "What guidance do I need to reach my goals?",
                ],
                [
                    "Starting Point",
                    "Current Position",
                    "Challenges Ahead",
                    "Hidden Influences",
                    "Guidance",
                    "Outcome",
                ],
            ),
            "relationship_harmony": Spread(
                "relationship_harmony",
                "This spread assesses the harmony in your relationship, examining strengths, weaknesses, hidden influences, and offering advice for improvement. It’s perfect for gaining clarity on how to enhance and nurture your relationship.",
                [
                    "How can I improve my relationship with my partner?",
                    "What are the hidden influences affecting our harmony?",
                    "What steps can we take to strengthen our bond?",
                ],
                [
                    "You",
                    "Your Partner",
                    "Strengths",
                    "Weaknesses",
                    "Hidden Influences",
                    "Advice",
                    "Outcome",
                ],
            ),
            "career_path": Spread(
                "career_path",
                "This spread offers insight into your career trajectory, identifying current challenges, strengths, opportunities, hidden influences, advice, and potential outcomes. Use it to navigate career decisions and understand the best path forward.",
                [
                    "What are my career strengths and challenges?",
                    "How can I overcome obstacles in my job?",
                    "What opportunities should I focus on for career success?",
                ],
                [
                    "Current Position",
                    "Challenges",
                    "Strengths",
                    "Opportunities",
                    "Hidden Influences",
                    "Advice",
                    "Outcome",
                ],
            ),
            "healing": Spread(
                "healing",
                "The Healing spread focuses on your present state, underlying issues, healing path, supportive influences, obstacles, and advice for recovery. It’s designed to provide insight into physical, emotional, and spiritual healing.",
                [
                    "What are the underlying issues affecting my health?",
                    "What steps should I take on my healing path?",
                    "What supportive influences can aid my recovery?",
                ],
                [
                    "Present State",
                    "Underlying Issues",
                    "Healing Path",
                    "Supportive Influences",
                    "Obstacles",
                    "Healing Advice",
                    "Outcome",
                ],
            ),
            "decision_making": Spread(
                "decision_making",
                "This spread helps in making decisions by evaluating current situations, options, pros and cons, advice, and likely outcomes. It’s useful for weighing different choices and understanding the best course of action.",
                [
                    "What are the pros and cons of my options?",
                    "What is the best choice for my situation?",
                    "What are the likely outcomes of each decision?",
                ],
                [
                    "Current Situation",
                    "Option 1",
                    "Option 2",
                    "Pros of Option 1",
                    "Cons of Option 1",
                    "Pros of Option 2",
                    "Cons of Option 2",
                    "Advice",
                    "Likely Outcome",
                ],
            ),
            "spiritual_growth": Spread(
                "spiritual_growth",
                "The Spiritual Growth spread aids in your spiritual development by examining current state, past influences, lessons, challenges, guidance, and future spiritual state. Use it to understand your spiritual journey and how to enhance it.",
                [
                    "What is my current spiritual state?",
                    "What lessons do I need to learn?",
                    "How can I overcome spiritual challenges?",
                ],
                [
                    "Current Spiritual State",
                    "Past Influences",
                    "Lessons to Learn",
                    "Spiritual Challenges",
                    "Guidance",
                    "Future Spiritual State",
                ],
            ),
            "new_beginnings": Spread(
                "new_beginnings",
                "This spread helps navigate new beginnings by examining current situations, what to let go, resources, challenges, action steps, and long-term outcomes. It’s perfect for understanding how to start fresh and what to focus on for a successful new beginning.",
                [
                    "What should I let go of to start anew?",
                    "What resources are available to me?",
                    "What action steps should I take for success?",
                ],
                [
                    "Current Situation",
                    "What to Let Go",
                    "Resources Available",
                    "Potential Challenges",
                    "Action Steps",
                    "Long-Term Outcome",
                ],
            ),
            "inner_conflict": Spread(
                "inner_conflict",
                "The Inner Conflict spread resolves inner conflicts by examining current conflict, causes, internal and external influences, advice, and potential resolutions. It’s useful for understanding and overcoming internal struggles.",
                [
                    "What is causing my inner conflict?",
                    "What are the internal and external influences?",
                    "What steps can I take to resolve this conflict?",
                ],
                [
                    "Current Conflict",
                    "Underlying Cause",
                    "Internal Influences",
                    "External Influences",
                    "Advice",
                    "Potential Resolution",
                ],
            ),
            "financial_insight": Spread(
                "financial_insight",
                "This spread provides financial insights by evaluating current situations, income sources, expenses, hidden influences, advice, and future outlook. Use it to gain clarity on your financial health and make informed decisions.",
                [
                    "What is my current financial situation?",
                    "What hidden factors affect my finances?",
                    "What steps can I take to improve my financial outlook?",
                ],
                [
                    "Current Financial Situation",
                    "Income Sources",
                    "Expenses",
                    "Hidden Financial Influences",
                    "Financial Advice",
                    "Future Financial Outlook",
                ],
            ),
            "personal_growth": Spread(
                "personal_growth",
                "The Personal Growth spread focuses on your development by assessing current state, strengths, weaknesses, opportunities, challenges, guidance, and future state. It’s designed to help you understand your growth path and how to achieve your goals.",
                [
                    "What are my strengths and weaknesses?",
                    "What opportunities should I pursue for growth?",
                    "What guidance do I need to achieve my personal goals?",
                ],
                [
                    "Current State",
                    "Strengths",
                    "Weaknesses",
                    "Opportunities for Growth",
                    "Challenges to Overcome",
                    "Guidance",
                    "Future State",
                ],
            ),
            "life_purpose": Spread(
                "life_purpose",
                "This spread explores your life purpose by examining current situation, talents, lessons, obstacles, influences, guidance, life purpose, and future path. Use it to understand your unique path and how to fulfill your life’s mission.",
                [
                    "What is my current life situation?",
                    "What talents and skills should I focus on?",
                    "What is my life purpose and how can I achieve it?",
                ],
                [
                    "Current Life Situation",
                    "Talents and Skills",
                    "Life Lessons",
                    "Obstacles",
                    "Supportive Influences",
                    "Guidance",
                    "Life Purpose",
                    "Future Path",
                ],
            ),
            "life_path": Spread(
                "life_path",
                "The Life Path spread maps out your journey by evaluating early life, recent past, present, near future, distant future, hidden influences, lessons, and ultimate potential. Use it to gain a comprehensive understanding of your life’s trajectory and how to achieve your highest potential.",
                [
                    "What lessons from my early life influence me now?",
                    "What are my hidden influences?",
                    "What is my ultimate potential and how can I reach it?",
                ],
                [
                    "Early Life",
                    "Recent Past",
                    "Present",
                    "Near Future",
                    "Distant Future",
                    "Hidden Influences",
                    "Life Lessons",
                    "Ultimate Potential",
                ],
            ),
            "elemental_balance": Spread(
                "elemental_balance",
                "This spread provides insight into balancing the five elements (Fire, Water, Air, Earth, Spirit) within your life. Use it to understand how each element influences your current situation and to seek guidance on achieving harmony. Ideal for questions about energy balance, personal well-being, and spiritual growth.",
                [
                    "How can I balance different aspects of my life?",
                    "What elements need more focus?",
                    "How can I achieve spiritual harmony?",
                ],
                ["Fire", "Water", "Air", "Earth", "Spirit", "Guidance"],
            ),
            "conflict_resolution": Spread(
                "conflict_resolution",
                "The Conflict Resolution spread is designed to uncover the nature of a conflict, providing perspectives from all involved parties, identifying root causes, and suggesting possible resolutions. It’s ideal for resolving interpersonal disputes, misunderstandings, or internal conflicts.",
                [
                    "What is the root cause of this conflict?",
                    "How can I understand the other person's perspective?",
                    "What steps can I take to resolve this issue?",
                ],
                [
                    "Nature of the Conflict",
                    "Your Perspective",
                    "The Other Person's Perspective",
                    "Root Cause",
                    "Possible Resolution",
                    "Advice",
                    "Outcome",
                ],
            ),
            "creativity": Spread(
                "creativity",
                "This spread aims to unblock creative potential by identifying current creative blocks, sources of inspiration, hidden talents, and external influences. It’s perfect for artists, writers, or anyone seeking to enhance their creativity.",
                [
                    "What is blocking my creativity?",
                    "Where can I find inspiration?",
                    "What hidden talents can I tap into?",
                ],
                [
                    "Current Creative Block",
                    "Source of Inspiration",
                    "Hidden Talents",
                    "External Influences",
                    "Creative Potential",
                    "Action Steps",
                    "Outcome",
                ],
            ),
            "self_discovery": Spread(
                "self_discovery",
                "The Self-Discovery spread helps you explore your self-perception, strengths, weaknesses, hidden talents, and life goals. It provides guidance on personal growth and future potential.",
                [
                    "What are my strengths and weaknesses?",
                    "What hidden talents do I possess?",
                    "What steps can I take towards my life goals?",
                ],
                [
                    "Current Self-Perception",
                    "Strengths",
                    "Weaknesses",
                    "Hidden Talents",
                    "Life Goals",
                    "Guidance",
                    "Future Self",
                ],
            ),
            "manifestation": Spread(
                "manifestation",
                "This spread guides you through the process of manifestation by examining your current desires, obstacles, supportive forces, hidden influences, and action steps. It’s ideal for those looking to bring their dreams into reality.",
                [
                    "What is my current desire?",
                    "What obstacles are in my way?",
                    "What steps should I take to manifest my goals?",
                ],
                [
                    "Current Desire",
                    "Obstacles",
                    "Supportive Forces",
                    "Hidden Influences",
                    "Action Steps",
                    "Outcome",
                    "Long-Term Potential",
                ],
            ),
            "change_and_transition": Spread(
                "change_and_transition",
                "The Change and Transition spread helps you navigate life changes by examining your current situation, what to leave behind, what to take forward, challenges, support systems, and guidance. It’s perfect for those undergoing significant transitions.",
                [
                    "What should I leave behind?",
                    "What challenges lie ahead?",
                    "How can I best navigate this transition?",
                ],
                [
                    "Current Situation",
                    "What to Leave Behind",
                    "What to Take Forward",
                    "Challenges Ahead",
                    "Support Systems",
                    "Guidance",
                    "Outcome",
                ],
            ),
            "dream_interpretation": Spread(
                "dream_interpretation",
                "This spread provides insight into the meaning of your dreams by examining the overview, subconscious influences, hidden messages, emotional impact, guidance, and how to apply the message. Use it for understanding recurring dreams, deciphering symbolic messages, and gaining clarity on subconscious thoughts.",
                [
                    "What does my dream mean?",
                    "What subconscious influences are at play?",
                    "How can I apply the message of my dream?",
                ],
                [
                    "Overview of the Dream",
                    "Subconscious Influences",
                    "Hidden Messages",
                    "Emotional Impact",
                    "Guidance",
                    "How to Apply the Message",
                ],
            ),
            "family_dynamics": Spread(
                "family_dynamics",
                "The Family Dynamics spread explores your role within your family, other members’ roles, strengths and challenges in relationships, hidden influences, advice, and outcomes. It’s useful for understanding and improving family relationships.",
                [
                    "What is my role in the family?",
                    "What are the strengths and challenges in our relationships?",
                    "How can we improve our family dynamics?",
                ],
                [
                    "Your Role",
                    "Other Family Member's Role",
                    "Strengths in the Relationship",
                    "Challenges in the Relationship",
                    "Hidden Influences",
                    "Advice",
                    "Outcome",
                ],
            ),
            "spiritual_awakening": Spread(
                "spiritual_awakening",
                "This spread aids in your spiritual awakening by examining your current spiritual state, blockages, guidance, new insights, spiritual growth, and long-term potential. It’s ideal for those on a path of spiritual enlightenment.",
                [
                    "What is blocking my spiritual growth?",
                    "What guidance do I need?",
                    "What is my long-term spiritual potential?",
                ],
                [
                    "Current Spiritual State",
                    "Blockages",
                    "Guidance",
                    "New Insights",
                    "Spiritual Growth",
                    "Long-Term Potential",
                ],
            ),
            "personal_power": Spread(
                "personal_power",
                "The Personal Power spread helps you understand and enhance your personal power by examining your current power level, hidden strengths, external influences, obstacles, guidance, and future power potential.",
                [
                    "What are my hidden strengths?",
                    "What obstacles are diminishing my power?",
                    "How can I achieve my future power potential?",
                ],
                [
                    "Current Power Level",
                    "Hidden Strengths",
                    "External Influences",
                    "Obstacles",
                    "Guidance",
                    "Future Power Potential",
                ],
            ),
            "relationship_potential": Spread(
                "relationship_potential",
                "This spread assesses the potential of a relationship by examining your feelings, your partner’s feelings, strengths and weaknesses in the relationship, hidden influences, advice, and long-term potential. It’s ideal for understanding the dynamics and future of a relationship.",
                [
                    "What are my partner’s true feelings?",
                    "What are the strengths and weaknesses of our relationship?",
                    "What is the long-term potential of this relationship?",
                ],
                [
                    "Your Feelings",
                    "Their Feelings",
                    "Strengths in the Relationship",
                    "Weaknesses in the Relationship",
                    "Hidden Influences",
                    "Advice",
                    "Long-Term Potential",
                ],
            ),
            "decision_clarifier": Spread(
                "decision_clarifier",
                "The Decision Clarifier spread aids in making decisions by examining your current situation, two options, factors to consider, advice for each option, and likely outcomes. It’s useful for weighing different choices and finding clarity.",
                [
                    "What are the factors I need to consider?",
                    "What is the best choice for my situation?",
                    "What are the likely outcomes of each decision?",
                ],
                [
                    "Current Situation",
                    "Option 1",
                    "Option 2",
                    "Factors to Consider",
                    "Advice for Option 1",
                    "Advice for Option 2",
                    "Likely Outcome for Option 1",
                    "Likely Outcome for Option 2",
                ],
            ),
            "soul_purpose": Spread(
                "soul_purpose",
                "The Soul Purpose spread explores your current life path, soul desires, challenges, life lessons, guidance, future potential, and ultimate soul purpose. It’s ideal for those seeking to understand and fulfill their soul’s mission.",
                [
                    "What is my current life path?",
                    "What are my soul’s desires?",
                    "What is my ultimate soul purpose?",
                ],
                [
                    "Current Life Path",
                    "Soul Desires",
                    "Challenges",
                    "Life Lessons",
                    "Guidance",
                    "Future Potential",
                    "Ultimate Soul Purpose",
                ],
            ),
            "love_and_relationship": Spread(
                "love_and_relationship",
                "This spread examines the status of your love life, your feelings, your partner’s feelings, strengths, weaknesses, hidden influences, advice, and outcome. It’s perfect for gaining clarity on your romantic relationships.",
                [
                    "What are my partner’s true feelings?",
                    "What are the strengths and weaknesses of our relationship?",
                    "What is the likely outcome of our relationship?",
                ],
                [
                    "Current Relationship Status",
                    "Your Feelings",
                    "Partner's Feelings",
                    "Strengths",
                    "Weaknesses",
                    "Hidden Influences",
                    "Advice",
                    "Outcome",
                ],
            ),
            "clarity": Spread(
                "clarity",
                "The Clarity spread helps you gain clear understanding of a situation by examining your current situation, what is unclear, hidden influences, advice, and likely outcome. It’s useful for resolving confusion and finding direction.",
                [
                    "What is unclear in my situation?",
                    "What hidden influences should I be aware of?",
                    "What steps can I take to achieve clarity?",
                ],
                [
                    "Current Situation",
                    "What is Unclear",
                    "Hidden Influences",
                    "Advice",
                    "Likely Outcome",
                ],
            ),
            "empowerment": Spread(
                "empowerment",
                "The Empowerment spread focuses on empowering you by examining your current situation, strengths, weaknesses, opportunities, challenges, guidance, and outcome. It’s ideal for those seeking to enhance their personal power and achieve goals.",
                [
                    "What are my strengths and weaknesses?",
                    "What opportunities should I pursue?",
                    "How can I achieve empowerment?",
                ],
                [
                    "Current Situation",
                    "Strengths",
                    "Weaknesses",
                    "Opportunities",
                    "Challenges",
                    "Guidance",
                    "Outcome",
                ],
            ),
            "soulmate": Spread(
                "soulmate",
                "The Soulmate spread explores the dynamics of your relationship with your soulmate, examining your role, your soulmate’s role, strengths, challenges, guidance, and long-term potential. It’s useful for understanding and nurturing soulmate connections.",
                [
                    "What is my role in this relationship?",
                    "What are the strengths and challenges of our connection?",
                    "What is the long-term potential of our relationship?",
                ],
                [
                    "Current Relationship Status",
                    "Your Role",
                    "Soulmate's Role",
                    "Strengths in the Relationship",
                    "Challenges in the Relationship",
                    "Guidance",
                    "Long-Term Potential",
                ],
            ),
            "intuition": Spread(
                "intuition",
                "This spread helps enhance your intuition by examining your current intuitive state, blockages, guidance, hidden insights, action steps, and future intuitive potential. It’s perfect for those seeking to develop and trust their intuition.",
                [
                    "What is blocking my intuition?",
                    "What guidance do I need?",
                    "What is my future intuitive potential?",
                ],
                [
                    "Current Intuitive State",
                    "Blockages",
                    "Guidance",
                    "Hidden Insights",
                    "Action Steps",
                    "Future Intuitive Potential",
                ],
            ),
            "weekly": Spread(
                "weekly",
                "The Weekly spread provides a daily outlook for the week ahead, offering insight into key events and influences for each day from Monday to Sunday. It’s ideal for planning and preparing for the week.",
                [
                    "What should I focus on each day this week?",
                    "What challenges might I face?",
                    "What opportunities should I look out for?",
                ],
                [
                    "Monday",
                    "Tuesday",
                    "Wednesday",
                    "Thursday",
                    "Friday",
                    "Saturday",
                    "Sunday",
                ],
            ),
        }

    def perform_reading(self, spread_name, upright_only=False):
        if spread_name in self.spreads:
            spread = self.spreads[spread_name]
            self.deck.shuffle_deck()  # Shuffle the deck before each spread
            spread.draw_cards(self.deck, upright_only=upright_only)
            spread.display()
        else:
            print(f"Spread '{spread_name}' not found.")
